/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Generate QR PDF for playlist songs
 */
export const ExportPlaylistQrParams = zod.object({
  "playlistId": zod.int()
})

export const exportPlaylistQrQueryPaperSizeDefault = `A4`;

export const ExportPlaylistQrQueryParams = zod.object({
  "paperSize": zod.enum(['A4', 'LETTER', 'LEGAL', 'A3', 'A5', 'TABLOID']).default(exportPlaylistQrQueryPaperSizeDefault)
})

export const ExportPlaylistQrResponse = zod.unknown()

/**
 * @summary Generate info PDF for playlist songs
 */
export const ExportPlaylistInfoParams = zod.object({
  "playlistId": zod.int()
})

export const exportPlaylistInfoQueryPaperSizeDefault = `A4`;

export const ExportPlaylistInfoQueryParams = zod.object({
  "paperSize": zod.enum(['A4', 'LETTER', 'LEGAL', 'A3', 'A5', 'TABLOID']).default(exportPlaylistInfoQueryPaperSizeDefault)
})

export const ExportPlaylistInfoResponse = zod.unknown()

/**
 * @summary Generate interleaved info+QR PDF for playlist songs, printer duplex
 */
export const ExportPlaylistDuplexParams = zod.object({
  "playlistId": zod.int()
})

export const exportPlaylistDuplexQueryPaperSizeDefault = `A4`;

export const ExportPlaylistDuplexQueryParams = zod.object({
  "paperSize": zod.enum(['A4', 'LETTER', 'LEGAL', 'A3', 'A5', 'TABLOID']).default(exportPlaylistDuplexQueryPaperSizeDefault)
})

export const ExportPlaylistDuplexResponse = zod.unknown()

