/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Get the current state of a game session, must be a player in it
 */
export const getSessionParams = zod.object({
  "sessionId": zod.number()
})

/**
 * @summary Get the current round's YouTube link-out, must be the round's DJ
 */
export const getCurrentRoundLinkOutParams = zod.object({
  "sessionId": zod.number()
})

/**
 * @summary Get the most recently completed session's results export for a group
 */
export const getResultsParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Get a group's active game session, must be a player in it
 */
export const getActiveSessionForGroupParams = zod.object({
  "groupId": zod.number()
})

