/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Get the current state of a game session, must be a player in it
 */
export const GetSessionParams = zod.object({
  "sessionId": zod.int()
})

export const GetSessionResponse = zod.unknown()

/**
 * @summary Get the current round's YouTube link-out, must be the round's DJ
 */
export const GetCurrentRoundLinkOutParams = zod.object({
  "sessionId": zod.int()
})

export const GetCurrentRoundLinkOutResponse = zod.unknown()

/**
 * @summary Get the most recently completed session's results export for a group
 */
export const GetResultsParams = zod.object({
  "groupId": zod.int()
})

export const GetResultsResponse = zod.unknown()

/**
 * @summary Get a group's active game session, must be a player in it
 */
export const GetActiveSessionForGroupParams = zod.object({
  "groupId": zod.int()
})

export const GetActiveSessionForGroupResponse = zod.unknown()

