/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Report a song's metadata as wrong, available to any authenticated user on any card
 */
export const SubmitReportParams = zod.object({
  "songId": zod.int()
})


export const submitReportBodySuggestedCorrectYearMin = 1000;



export const SubmitReportBody = zod.object({
  "message": zod.string().min(1),
  "suggestedCorrectYear": zod.int().min(submitReportBodySuggestedCorrectYearMin).optional(),
  "sources": zod.string().optional()
})

export const SubmitReportResponse = zod.unknown()

/**
 * @summary Confirm a song's metadata is correct; available only on cards not yet at the verified tier
 */
export const SubmitConfirmationParams = zod.object({
  "songId": zod.int()
})

export const SubmitConfirmationResponse = zod.unknown()

