/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Report a song's metadata as wrong, available to any authenticated user on any card
 */
export const submitReportParams = zod.object({
  "songId": zod.number()
})


export const submitReportBodySuggestedCorrectYearMin = 1000;



export const submitReportBody = zod.object({
  "message": zod.string().min(1),
  "suggestedCorrectYear": zod.number().min(submitReportBodySuggestedCorrectYearMin).optional(),
  "sources": zod.string().optional()
})

/**
 * @summary Confirm a song's metadata is correct; available only on cards not yet at the verified tier
 */
export const submitConfirmationParams = zod.object({
  "songId": zod.number()
})

