/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Page through verified (artist, title, release year) triples
 */
export const verifiedSongsQueryPageablePageMin = 0;




export const VerifiedSongsQueryParams = zod.object({
  "pageable": zod.object({
  "page": zod.int().min(verifiedSongsQueryPageablePageMin).optional(),
  "size": zod.int().min(1).optional(),
  "sort": zod.array(zod.string()).optional()
})
})

export const VerifiedSongsResponse = zod.unknown()

