services:
  db:
    image: pgvector/pgvector:pg18
    container_name: my-hitster-postgres
    restart: always
    ports:
      - "5500:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - hitster_postgres_data:/var/lib/postgresql

  analytics-db:
    image: postgres:18
    container_name: my-hitster-analytics-postgres
    restart: always
    ports:
      - "5501:5432"
    environment:
      POSTGRES_DB: ${ANALYTICS_DB_NAME}
      POSTGRES_USER: ${ANALYTICS_DB_USERNAME}
      POSTGRES_PASSWORD: ${ANALYTICS_DB_PASSWORD}
    volumes:
      - hitster_analytics_postgres_data:/var/lib/postgresql

volumes:
  hitster_postgres_data:
  hitster_analytics_postgres_data: