/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Bulk-enqueue YouTube IDs into the seeding backlog, admin only; already-known songs are skipped
 */
export const enqueueBodyItem = zod.string()
export const enqueueBody = zod.array(enqueueBodyItem)

