/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Bulk-enqueue a YouTube playlist link and/or video IDs into the seeding backlog, admin only; already-known songs are skipped
 */
export const enqueueBody = zod.object({
  "playlistLink": zod.string().optional(),
  "youtubeIds": zod.array(zod.string()).optional()
})

