/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Bulk-enqueue a YouTube playlist link and/or video IDs into the seeding backlog, admin only; already-known songs are skipped
 */
export const EnqueueBody = zod.object({
  "playlistLink": zod.string().optional(),
  "youtubeIds": zod.array(zod.string()).optional()
})

export const EnqueueResponse = zod.unknown()

/**
 * @summary Start draining the backlog now instead of waiting for the daily sweep, admin only; 409 when a drain is already running
 */
export const DrainNowResponse = zod.unknown()

/**
 * @summary Backlog status, admin only: pending count, processed today, quota remaining, and recent rechecks of provisional answers
 */
export const BacklogStatusResponse = zod.unknown()

