/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Search the song catalog by artist/title keyword or YouTube link/ID
 */
export const SearchSongsQueryParams = zod.object({
  "query": zod.string()
})

export const SearchSongsResponse = zod.unknown()

/**
 * @summary Recommend newest verified catalog songs, paged
 */
export const recommendSongsQueryPageDefault = 0;
export const recommendSongsQuerySizeDefault = 20;

export const RecommendSongsQueryParams = zod.object({
  "page": zod.int().default(recommendSongsQueryPageDefault),
  "size": zod.int().default(recommendSongsQuerySizeDefault)
})

export const RecommendSongsResponse = zod.unknown()

