/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Search the song catalog by artist/title keyword or YouTube link/ID
 */
export const searchSongsQueryParams = zod.object({
  "query": zod.string()
})

