/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Fetch song metadata from a YouTube URL
 */
export const GetSongMetadataQueryParams = zod.object({
  "youtubeUrl": zod.string()
})

export const GetSongMetadataResponse = zod.unknown()

