/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Resolve a song's open reports, admin only; applies the admin's chosen year and verification status unconditionally, overriding even a locked, VERIFIED song
 */
export const resolveParams = zod.object({
  "songId": zod.number()
})

export const resolveBodyCorrectedYearMin = 1000;



export const resolveBody = zod.object({
  "correctedYear": zod.number().min(resolveBodyCorrectedYearMin).optional(),
  "verificationStatus": zod.enum(['UNVERIFIED', 'VERIFIED', 'NEEDS_REVIEW', 'MANUAL_ENTRY'])
})

/**
 * @summary Dismiss a song's open reports, admin only
 */
export const dismissParams = zod.object({
  "songId": zod.number()
})

