/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Uphold a song's open reports, admin only; a locked song's year stays immutable, an editable song moves to manual entry
 */
export const upholdParams = zod.object({
  "songId": zod.number()
})

/**
 * @summary Dismiss a song's open reports, admin only
 */
export const dismissParams = zod.object({
  "songId": zod.number()
})

