/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Resolve a song's open reports, admin only; applies the admin's chosen year and verification status unconditionally, overriding even a locked, VERIFIED song
 */
export const ResolveParams = zod.object({
  "songId": zod.int()
})

export const resolveBodyCorrectedYearMin = 1000;



export const ResolveBody = zod.object({
  "correctedYear": zod.int().min(resolveBodyCorrectedYearMin).optional(),
  "verificationStatus": zod.enum(['UNVERIFIED', 'VERIFIED', 'NEEDS_REVIEW', 'MANUAL_ENTRY'])
})

export const ResolveResponse = zod.unknown()

/**
 * @summary Dismiss a song's open reports, admin only
 */
export const DismissParams = zod.object({
  "songId": zod.int()
})

export const DismissResponse = zod.unknown()

/**
 * @summary Review queue ordered by priority tier, admin only; every ranking signal is exposed rather than a single score
 */
export const ReviewQueueResponse = zod.unknown()

