/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Load a group's recent chat history, members only
 */
export const GetHistoryParams = zod.object({
  "groupId": zod.int()
})

export const GetHistoryResponse = zod.unknown()

