/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Load a group's recent chat history, members only
 */
export const getHistoryParams = zod.object({
  "groupId": zod.number()
})

