/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Upload the current user's pixelized profile picture
 */
export const uploadOwnAvatarBody = zod.object({
  "avatar": zod.instanceof(File)
})

/**
 * @summary Read a playlist's custom cover, if it has one
 */
export const readPlaylistCoverParams = zod.object({
  "playlistId": zod.number()
})

/**
 * @summary Upload a pixelized playlist cover, replacing any previous one
 */
export const uploadPlaylistCoverParams = zod.object({
  "playlistId": zod.number()
})

export const uploadPlaylistCoverBody = zod.object({
  "cover": zod.instanceof(File)
})

/**
 * @summary Read a user's custom avatar, if they have one
 */
export const readUserAvatarParams = zod.object({
  "userId": zod.number()
})

