/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Upload the current user's pixelized profile picture
 */
export const UploadOwnAvatarBody = zod.object({
  "avatar": zod.instanceof(Blob)
})

export const UploadOwnAvatarResponse = zod.unknown()

/**
 * @summary Read a playlist's custom cover, if it has one, must be able to read the playlist
 */
export const ReadPlaylistCoverParams = zod.object({
  "playlistId": zod.int()
})

export const ReadPlaylistCoverResponse = zod.unknown()

/**
 * @summary Upload a pixelized playlist cover, replacing any previous one
 */
export const UploadPlaylistCoverParams = zod.object({
  "playlistId": zod.int()
})

export const UploadPlaylistCoverBody = zod.object({
  "cover": zod.instanceof(Blob)
})

export const UploadPlaylistCoverResponse = zod.unknown()

/**
 * @summary Read a user's custom avatar, if they have one
 */
export const ReadUserAvatarParams = zod.object({
  "userId": zod.int()
})

export const ReadUserAvatarResponse = zod.unknown()

