/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Verify an email address using a verification token
 */



export const VerifyEmailBody = zod.object({
  "token": zod.string().min(1)
})

export const VerifyEmailResponse = zod.unknown()

/**
 * @summary Resend the email verification link, rate-limited
 */



export const ResendVerificationBody = zod.object({
  "email": zod.email().min(1)
})

export const ResendVerificationResponse = zod.unknown()

/**
 * @summary Register a new user
 */
export const registerBodyUsernameMin = 3;
export const registerBodyUsernameMax = 20;


export const registerBodyPasswordMin = 6;
export const registerBodyPasswordMax = 2147483647;



export const RegisterBody = zod.object({
  "username": zod.string().min(registerBodyUsernameMin).max(registerBodyUsernameMax),
  "email": zod.email().min(1),
  "password": zod.string().min(registerBodyPasswordMin).max(registerBodyPasswordMax)
})

export const RegisterResponse = zod.unknown()

/**
 * @summary Refresh access token using refresh token cookie
 */
export const RefreshResponse = zod.unknown()

/**
 * @summary Request a password reset email, always succeeds regardless of whether the email exists
 */



export const RequestPasswordResetBody = zod.object({
  "email": zod.email().min(1)
})

export const RequestPasswordResetResponse = zod.unknown()

/**
 * @summary Confirm a password reset using a reset token
 */

export const confirmPasswordResetBodyNewPasswordMin = 6;
export const confirmPasswordResetBodyNewPasswordMax = 2147483647;



export const ConfirmPasswordResetBody = zod.object({
  "token": zod.string().min(1),
  "newPassword": zod.string().min(confirmPasswordResetBodyNewPasswordMin).max(confirmPasswordResetBodyNewPasswordMax)
})

export const ConfirmPasswordResetResponse = zod.unknown()

/**
 * @summary Logout and clear auth tokens
 */
export const LogoutResponse = zod.unknown()

/**
 * @summary Login with username/email and password
 */




export const LoginBody = zod.object({
  "email": zod.string().min(1),
  "password": zod.string().min(1),
  "rememberMe": zod.boolean().optional()
})

export const LoginResponse = zod.unknown()

/**
 * @summary Complete login for a two-factor-enabled account
 */




export const VerifyTwoFactorBody = zod.object({
  "pendingToken": zod.string().min(1),
  "code": zod.string().min(1)
})

export const VerifyTwoFactorResponse = zod.unknown()

/**
 * @summary Start TOTP two-factor setup for the current account
 */
export const SetupTwoFactorResponse = zod.unknown()

/**
 * @summary Disable two-factor authentication, requires the current password or a valid code
 */
export const DisableTwoFactorBody = zod.object({
  "currentPassword": zod.string().optional(),
  "code": zod.string().optional()
})

export const DisableTwoFactorResponse = zod.unknown()

/**
 * @summary Confirm TOTP two-factor setup with a code from the authenticator app
 */



export const ConfirmTwoFactorBody = zod.object({
  "code": zod.string().min(1)
})

export const ConfirmTwoFactorResponse = zod.unknown()

