# Database
spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
# JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# AI microservice
ai.service.base-url=${AI_SERVICE_URL:http://localhost:8000}
ai.service.internal-api-key=${INTERNAL_SERVICE_API_KEY}
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=604800000
# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
# OAuth2 redirect
app.oauth2.redirect-uri=${FRONTEND_URL}/oauth2/redirect
server.forward-headers-strategy=native
# Environment
app.env=${APP_ENV:dev}