/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Import a list of YouTube video IDs or links immediately, optionally linking every resolved or already-known song into a target playlist
 */
export const importImmediatelyBody = zod.object({
  "playlistLink": zod.string().optional(),
  "videoIdsOrLinks": zod.array(zod.string()).optional(),
  "targetPlaylistId": zod.number().optional(),
  "importJobId": zod.string().optional()
})

/**
 * @summary Expand a YouTube playlist link or id into its video ids for review before importing
 */
export const expandPlaylistBody = zod.object({
  "playlistLink": zod.string().optional()
})

