/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Import a list of YouTube video IDs or links immediately; already-known songs are skipped
 */
export const importImmediatelyBody = zod.object({
  "playlistLink": zod.string().optional(),
  "videoIdsOrLinks": zod.array(zod.string()).optional()
})

