/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Create a group, the creator becomes its admin
 */
export const CreateGroupBody = zod.object({
  "displayName": zod.string().optional(),
  "avatarUrl": zod.string().optional()
})

export const CreateGroupResponse = zod.unknown()

/**
 * @summary Leave the group's voice room
 */
export const LeaveVoiceParams = zod.object({
  "groupId": zod.int()
})

export const LeaveVoiceResponse = zod.unknown()

/**
 * @summary Join the group's voice room
 */
export const JoinVoiceParams = zod.object({
  "groupId": zod.int()
})

export const JoinVoiceResponse = zod.unknown()

/**
 * @summary Start a game session, admin only, locks the group to new members
 */
export const StartGameSessionParams = zod.object({
  "groupId": zod.int()
})

export const StartGameSessionResponse = zod.unknown()

/**
 * @summary Start a game session from reviewed song ids, admin only, locks the group to new members
 */
export const StartSessionWithSongsParams = zod.object({
  "groupId": zod.int()
})

export const StartSessionWithSongsBody = zod.object({
  "songIds": zod.array(zod.int()).optional()
})

export const StartSessionWithSongsResponse = zod.unknown()

/**
 * @summary Start a game session from a playlist or pasted playlist link, admin only, locks the group to new members
 */
export const StartCustomSessionParams = zod.object({
  "groupId": zod.int()
})

export const StartCustomSessionBody = zod.object({
  "playlistId": zod.int().optional(),
  "playlistLink": zod.string().optional()
})

export const StartCustomSessionResponse = zod.unknown()

/**
 * @summary Generate a difficulty-tuned song set for review, admin only, starts nothing
 */
export const GenerateDifficultySetParams = zod.object({
  "groupId": zod.int()
})

export const GenerateDifficultySetBody = zod.object({
  "tier": zod.enum(['EASY', 'MEDIUM', 'HARD']).optional(),
  "targetCardCount": zod.int().optional()
})

export const GenerateDifficultySetResponse = zod.unknown()

/**
 * @summary Mark the current member reconnected
 */
export const ReconnectParams = zod.object({
  "groupId": zod.int()
})

export const ReconnectResponse = zod.unknown()

/**
 * @summary Promote another member to admin, admin only
 */
export const PromoteMember1Params = zod.object({
  "groupId": zod.int(),
  "memberId": zod.int()
})

export const PromoteMember1Response = zod.unknown()

/**
 * @summary Leave a group, removing the membership entirely
 */
export const LeaveGroupParams = zod.object({
  "groupId": zod.int()
})

export const LeaveGroupResponse = zod.unknown()

/**
 * @summary Mark the current member disconnected without ending their membership
 */
export const DisconnectParams = zod.object({
  "groupId": zod.int()
})

export const DisconnectResponse = zod.unknown()

/**
 * @summary Join a group via invite link or join code
 */
export const JoinGroupBody = zod.object({
  "inviteCode": zod.string().optional(),
  "joinCode": zod.string().optional(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.string().optional()
})

export const JoinGroupResponse = zod.unknown()

/**
 * @summary Update group settings, admin only
 */
export const UpdateGroupSettingsParams = zod.object({
  "groupId": zod.int()
})

export const UpdateGroupSettingsBody = zod.object({
  "playlistIds": zod.array(zod.int()).optional(),
  "djMode": zod.enum(['FIXED', 'ROTATING']).optional(),
  "winConditionCardCount": zod.int().optional(),
  "fixedDjMemberId": zod.int().optional()
})

export const UpdateGroupSettingsResponse = zod.unknown()

/**
 * @summary Get group information
 */
export const GetGroupParams = zod.object({
  "groupId": zod.int()
})

export const GetGroupResponse = zod.unknown()

/**
 * @summary Get the ICE server list for the group's voice room, member only
 */
export const GetVoiceTurnCredentialsParams = zod.object({
  "groupId": zod.int()
})

export const GetVoiceTurnCredentialsResponse = zod.unknown()

/**
 * @summary Preview a group by invite code, no membership or authentication required
 */
export const GetInvitePreview1Params = zod.object({
  "inviteCode": zod.string()
})

export const GetInvitePreview1Response = zod.unknown()

/**
 * @summary Check the logged-in user's active group membership, if any
 */
export const GetActiveMembershipResponse = zod.unknown()

