/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Create a group, the creator becomes its admin
 */
export const createGroupBody = zod.object({
  "displayName": zod.string().optional(),
  "avatarUrl": zod.string().optional()
})

/**
 * @summary Leave the group's voice room
 */
export const leaveVoiceParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Join the group's voice room
 */
export const joinVoiceParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Start a game session, admin only, locks the group to new members
 */
export const startGameSessionParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Mark the current member reconnected
 */
export const reconnectParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Promote another member to admin, admin only
 */
export const promoteMember1Params = zod.object({
  "groupId": zod.number(),
  "memberId": zod.number()
})

/**
 * @summary Leave a group, removing the membership entirely
 */
export const leaveGroupParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Mark the current member disconnected without ending their membership
 */
export const disconnectParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Join a group via invite link or join code
 */
export const joinGroupBody = zod.object({
  "inviteCode": zod.string().optional(),
  "joinCode": zod.string().optional(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.string().optional()
})

/**
 * @summary Update group settings, admin only
 */
export const updateGroupSettingsParams = zod.object({
  "groupId": zod.number()
})

export const updateGroupSettingsBody = zod.object({
  "playlistIds": zod.array(zod.number()).optional(),
  "djMode": zod.enum(['FIXED', 'ROTATING']).optional(),
  "winConditionCardCount": zod.number().optional()
})

/**
 * @summary Get group information
 */
export const getGroupParams = zod.object({
  "groupId": zod.number()
})

/**
 * @summary Get the ICE server list for the group's voice room, member only
 */
export const getVoiceTurnCredentialsParams = zod.object({
  "groupId": zod.number()
})

