/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Start a background import into a playlist, returning the job id immediately
 */
export const StartImportParams = zod.object({
  "playlistId": zod.int()
})

export const StartImportBody = zod.object({
  "videoIdsOrLinks": zod.array(zod.string()).optional(),
  "playlistLink": zod.string().optional()
})

export const StartImportResponse = zod.unknown()

/**
 * @summary Read one import job of the playlist, running or finished, with per-video results
 */
export const ImportJobParams = zod.object({
  "playlistId": zod.int(),
  "importJobId": zod.string()
})

export const ImportJobResponse = zod.unknown()

/**
 * @summary Read the playlist's running import with per-video progress, if any
 */
export const ActiveImportParams = zod.object({
  "playlistId": zod.int()
})

export const ActiveImportResponse = zod.unknown()

