/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Start a background import into a playlist, returning the job id immediately
 */
export const startImportParams = zod.object({
  "playlistId": zod.number()
})

export const startImportBody = zod.object({
  "videoIdsOrLinks": zod.array(zod.string()).optional(),
  "playlistLink": zod.string().optional()
})

/**
 * @summary Read the playlist's running import with per-video progress, if any
 */
export const activeImportParams = zod.object({
  "playlistId": zod.number()
})

