/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminReviewItemDTOVerificationStatus } from './adminReviewItemDTOVerificationStatus';
import type { AdminReviewItemDTOPriorityTier } from './adminReviewItemDTOPriorityTier';
import type { ReportSummaryDTO } from './reportSummaryDTO';

export interface AdminReviewItemDTO {
  songId?: number;
  songTitle?: string;
  artistName?: string;
  releaseYear?: number;
  verificationStatus?: AdminReviewItemDTOVerificationStatus;
  priorityTier?: AdminReviewItemDTOPriorityTier;
  openReportCount?: number;
  reportsConverge?: boolean;
  convergingYear?: number;
  convergingReportCount?: number;
  confirmationCount?: number;
  openReports?: ReportSummaryDTO[];
}
