/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AdminCatalogSeedingRequest {
  playlistLink?: string;
  youtubeIds?: string[];
}
