/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AdminReviewItemDTOVerificationStatus = typeof AdminReviewItemDTOVerificationStatus[keyof typeof AdminReviewItemDTOVerificationStatus];


export const AdminReviewItemDTOVerificationStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  MANUAL_ENTRY: 'MANUAL_ENTRY',
} as const;
