/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AdminReviewItemDTOPriorityTier = typeof AdminReviewItemDTOPriorityTier[keyof typeof AdminReviewItemDTOPriorityTier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminReviewItemDTOPriorityTier = {
  CONVERGING_REPORTS: 'CONVERGING_REPORTS',
  REPORTED_NO_CONVERGENCE: 'REPORTED_NO_CONVERGENCE',
  CONFIRMED_UNREPORTED: 'CONFIRMED_UNREPORTED',
  UNCONFIRMED_UNREPORTED: 'UNCONFIRMED_UNREPORTED',
} as const;
