/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SongMetadataResponse } from './songMetadataResponse';

export interface AiResponse {
  content?: SongMetadataResponse;
  model?: string;
  durationMs?: number;
  timestamp?: string;
  status?: string;
  rejectionReason?: string;
  rejectionDetail?: string;
}
