/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AuthResponse {
  id?: number;
  username?: string;
  email?: string;
  emailVerificationRequired?: boolean;
}
