/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type BacklogQueueItemDTOStatus = typeof BacklogQueueItemDTOStatus[keyof typeof BacklogQueueItemDTOStatus];


export const BacklogQueueItemDTOStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;
