/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type BacklogQueueItemDTOStatus = typeof BacklogQueueItemDTOStatus[keyof typeof BacklogQueueItemDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BacklogQueueItemDTOStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;
