/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BacklogQueueItemDTOStatus } from './backlogQueueItemDTOStatus';

export interface BacklogQueueItemDTO {
  youtubeId?: string;
  status?: BacklogQueueItemDTOStatus;
  failureReason?: string;
}
