/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BacklogQueueItemDTO } from './backlogQueueItemDTO';

export interface BacklogStatusDTO {
  pendingCount?: number;
  processedTodayCount?: number;
  dailyDrainQuota?: number;
  quotaRemainingToday?: number;
  queueItems?: BacklogQueueItemDTO[];
}
