/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BulkImportRequest {
  playlistLink?: string;
  videoIdsOrLinks?: string[];
  targetPlaylistId?: number;
  importJobId?: string;
}
