/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChatMessageDTO {
  id?: number;
  groupId?: number;
  senderId?: number;
  senderDisplayName?: string;
  content?: string;
  createdAt?: string;
}
