/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateSongRequestTagsItem } from './createSongRequestTagsItem';
import type { CreateSongRequestCountry } from './createSongRequestCountry';

export interface CreateSongRequest {
  /** @minLength 1 */
  artist: string;
  /** @minLength 1 */
  title: string;
  releaseYear?: number;
  /** @minLength 1 */
  youtubeId: string;
  /** @minLength 1 */
  gradientColor1: string;
  /** @minLength 1 */
  gradientColor2: string;
  tags?: CreateSongRequestTagsItem[];
  country?: CreateSongRequestCountry;
}
