/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateSongRequestTagsItem = typeof CreateSongRequestTagsItem[keyof typeof CreateSongRequestTagsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSongRequestTagsItem = {
  PLAYLIST: 'PLAYLIST',
  SPECIAL: 'SPECIAL',
  ANIME: 'ANIME',
} as const;
