/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateSongRequestCountry = typeof CreateSongRequestCountry[keyof typeof CreateSongRequestCountry];


export const CreateSongRequestCountry = {
  NONE: 'NONE',
  RO: 'RO',
} as const;
