/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface EnqueueResultDTO {
  enqueuedYoutubeIds?: string[];
  skippedAlreadyKnownYoutubeIds?: string[];
  skippedAlreadyQueuedYoutubeIds?: string[];
}
