/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ExportPlaylistInfoPaperSize = typeof ExportPlaylistInfoPaperSize[keyof typeof ExportPlaylistInfoPaperSize];


export const ExportPlaylistInfoPaperSize = {
  A4: 'A4',
  LETTER: 'LETTER',
  LEGAL: 'LEGAL',
  A3: 'A3',
  A5: 'A5',
  TABLOID: 'TABLOID',
} as const;
