/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ExportPlaylistQrPaperSize } from './exportPlaylistQrPaperSize';

export type ExportPlaylistQrParams = {
paperSize?: ExportPlaylistQrPaperSize;
};
