/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ExportPlaylistQrPaperSize = typeof ExportPlaylistQrPaperSize[keyof typeof ExportPlaylistQrPaperSize];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportPlaylistQrPaperSize = {
  A4: 'A4',
  LETTER: 'LETTER',
} as const;
