/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ExportPlaylistInfoPaperSize = typeof ExportPlaylistInfoPaperSize[keyof typeof ExportPlaylistInfoPaperSize];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportPlaylistInfoPaperSize = {
  A4: 'A4',
  LETTER: 'LETTER',
} as const;
