/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ExportPlaylistDuplexPaperSize } from './exportPlaylistDuplexPaperSize';

export type ExportPlaylistDuplexParams = {
paperSize?: ExportPlaylistDuplexPaperSize;
};
