/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ExportPlaylistDuplexPaperSize = typeof ExportPlaylistDuplexPaperSize[keyof typeof ExportPlaylistDuplexPaperSize];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportPlaylistDuplexPaperSize = {
  A4: 'A4',
  LETTER: 'LETTER',
  LEGAL: 'LEGAL',
  A3: 'A3',
  A5: 'A5',
  TABLOID: 'TABLOID',
} as const;
