/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GameSessionDTODjMode = typeof GameSessionDTODjMode[keyof typeof GameSessionDTODjMode];


export const GameSessionDTODjMode = {
  FIXED: 'FIXED',
  ROTATING: 'ROTATING',
} as const;
