/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GameSessionDTOStatus } from './gameSessionDTOStatus';
import type { GameSessionDTODjMode } from './gameSessionDTODjMode';
import type { PlayerDTO } from './playerDTO';
import type { RoundDTO } from './roundDTO';

export interface GameSessionDTO {
  id?: number;
  groupId?: number;
  status?: GameSessionDTOStatus;
  djMode?: GameSessionDTODjMode;
  winConditionCardCount?: number;
  currentRoundNumber?: number;
  players?: PlayerDTO[];
  currentRound?: RoundDTO;
}
