/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GameSessionDTOStatus = typeof GameSessionDTOStatus[keyof typeof GameSessionDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameSessionDTOStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
} as const;
