/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GameSessionDTODjMode = typeof GameSessionDTODjMode[keyof typeof GameSessionDTODjMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameSessionDTODjMode = {
  FIXED: 'FIXED',
  ROTATING: 'ROTATING',
} as const;
