/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GenerateDifficultySetRequestTier = typeof GenerateDifficultySetRequestTier[keyof typeof GenerateDifficultySetRequestTier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenerateDifficultySetRequestTier = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
} as const;
