/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GenerateDifficultySetRequestTier } from './generateDifficultySetRequestTier';

export interface GenerateDifficultySetRequest {
  tier?: GenerateDifficultySetRequestTier;
  targetCardCount?: number;
}
