/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GeneratedSongPreviewDTO {
  id?: number;
  title?: string;
  artists?: string[];
  releaseYear?: number;
}
