/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GenerateDifficultySetRequestTier = typeof GenerateDifficultySetRequestTier[keyof typeof GenerateDifficultySetRequestTier];


export const GenerateDifficultySetRequestTier = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
} as const;
