/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GroundTruthSongDTO } from './groundTruthSongDTO';

export interface GroundTruthSongsResponse {
  songs?: GroundTruthSongDTO[];
  page?: number;
  size?: number;
  totalElements?: number;
}
