/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GroupDetailDTODjMode = typeof GroupDetailDTODjMode[keyof typeof GroupDetailDTODjMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupDetailDTODjMode = {
  FIXED: 'FIXED',
  ROTATING: 'ROTATING',
} as const;
