/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GroupDetailDTOStatus = typeof GroupDetailDTOStatus[keyof typeof GroupDetailDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupDetailDTOStatus = {
  OPEN: 'OPEN',
  LOCKED: 'LOCKED',
} as const;
