/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GroupInvitePreviewMemberDTO } from './groupInvitePreviewMemberDTO';

export interface GroupInvitePreviewDTO {
  memberCount?: number;
  members?: GroupInvitePreviewMemberDTO[];
}
