/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GroupInvitePreviewMemberDTO {
  displayName?: string;
  avatarUrl?: string;
  isAdmin?: boolean;
}
