/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GroupDetailDTODjMode = typeof GroupDetailDTODjMode[keyof typeof GroupDetailDTODjMode];


export const GroupDetailDTODjMode = {
  FIXED: 'FIXED',
  ROTATING: 'ROTATING',
} as const;
