/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GroupDetailDTODjMode } from './groupDetailDTODjMode';
import type { GroupDetailDTOStatus } from './groupDetailDTOStatus';
import type { MemberDTO } from './memberDTO';
import type { PlaylistSummaryDTO } from './playlistSummaryDTO';

export interface GroupDetailDTO {
  id?: number;
  inviteCode?: string;
  joinCode?: string;
  status?: GroupDetailDTOStatus;
  djMode?: GroupDetailDTODjMode;
  fixedDjMemberId?: number;
  winConditionCardCount?: number;
  playlists?: PlaylistSummaryDTO[];
  members?: MemberDTO[];
  expiresAt?: string;
}
