/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GroupDetailDTOStatus = typeof GroupDetailDTOStatus[keyof typeof GroupDetailDTOStatus];


export const GroupDetailDTOStatus = {
  OPEN: 'OPEN',
  LOCKED: 'LOCKED',
} as const;
