/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GuessStateDTO {
  roundId?: number;
  artistCount?: number;
  correctArtistCount?: number;
  artistGuessingClosed?: boolean;
  titleGuessed?: boolean;
  titleCorrect?: boolean;
  tokenEarned?: boolean;
}
