/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ImportFromPlaylistResultDTO {
  importedCount?: number;
  skippedCount?: number;
}
