/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface JoinGroupRequest {
  inviteCode?: string;
  joinCode?: string;
  displayName?: string;
  avatarUrl?: string;
}
