/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LeaderboardEntryDTO {
  playerId?: number;
  displayName?: string;
  value?: number;
  rank?: number;
}
