/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MemberDTO {
  id?: number;
  userId?: number;
  displayName?: string;
  avatarUrl?: string;
  isAdmin?: boolean;
  isConnected?: boolean;
  isInVoice?: boolean;
  joinedAt?: string;
}
