/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PasswordResetConfirmRequest {
  /** @minLength 1 */
  token: string;
  /**
     * @minLength 6
     * @maxLength 2147483647
     */
  newPassword: string;
}
