/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PasswordResetConfirmRequest {
  /** @minLength 1 */
  token: string;
  /**
   * @minLength 6
   * @maxLength 2147483647
   */
  newPassword: string;
}
