/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PatientRecheckDTOOrigin = typeof PatientRecheckDTOOrigin[keyof typeof PatientRecheckDTOOrigin];


export const PatientRecheckDTOOrigin = {
  ADMIN_SEED: 'ADMIN_SEED',
  FAST_TIER_RECHECK: 'FAST_TIER_RECHECK',
  USER_ADD_RECHECK: 'USER_ADD_RECHECK',
} as const;
