/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PatientRecheckDTOStatus = typeof PatientRecheckDTOStatus[keyof typeof PatientRecheckDTOStatus];


export const PatientRecheckDTOStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;
