/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PatientRecheckDTOOrigin } from './patientRecheckDTOOrigin';
import type { PatientRecheckDTOStatus } from './patientRecheckDTOStatus';

export interface PatientRecheckDTO {
  youtubeId?: string;
  origin?: PatientRecheckDTOOrigin;
  status?: PatientRecheckDTOStatus;
  title?: string;
  artists?: string;
  provisionalYear?: number;
  patientYear?: number;
  enqueuedAt?: string;
  processedAt?: string;
}
