/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistMembershipExportDTO } from './playlistMembershipExportDTO';
import type { SongDTO } from './songDTO';
import type { GameSummary, SongPlayObservation } from '../game-history';

export interface PersonalDataExportDTO {
  id?: number;
  username?: string;
  email?: string;
  imageUrl?: string;
  authProvider?: string;
  authProviderId?: string;
  playlists?: PlaylistMembershipExportDTO[];
  submittedSongs?: SongDTO[];
  gameHistory?: GameSummary[];
  researchObservations?: SongPlayObservation[];
}
