/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistMembershipExportDTO } from './playlistMembershipExportDTO';
import type { SongDTO } from './songDTO';

export interface PersonalDataExportDTO {
  id?: number;
  username?: string;
  email?: string;
  imageUrl?: string;
  authProvider?: string;
  authProviderId?: string;
  playlists?: PlaylistMembershipExportDTO[];
  submittedSongs?: SongDTO[];
}
