/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PlaylistMembershipExportDTO {
  playlistId?: number;
  playlistName?: string;
  owner?: boolean;
  canRead?: boolean;
  canWrite?: boolean;
  canDelete?: boolean;
  displayName?: string;
  avatarUrl?: string;
  joinedAt?: string;
}
