/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PlayerDTOStatus = typeof PlayerDTOStatus[keyof typeof PlayerDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayerDTOStatus = {
  ACTIVE: 'ACTIVE',
  LEFT: 'LEFT',
} as const;
