/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistImportJobItemDTOStatus } from './playlistImportJobItemDTOStatus';

export interface PlaylistImportJobItemDTO {
  youtubeId?: string;
  status?: PlaylistImportJobItemDTOStatus;
  songId?: number;
  rawTitle?: string;
  rawChannelTitle?: string;
  resolvedTitle?: string;
  resolvedArtists?: string;
  resolvedReleaseYear?: number;
  resolvedColor?: string;
}
