/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PlaylistImportJobItemDTOStatus = typeof PlaylistImportJobItemDTOStatus[keyof typeof PlaylistImportJobItemDTOStatus];


export const PlaylistImportJobItemDTOStatus = {
  PENDING: 'PENDING',
  ALREADY_KNOWN: 'ALREADY_KNOWN',
  RESOLVED: 'RESOLVED',
  UNRESOLVED: 'UNRESOLVED',
} as const;
