/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PlaylistImportJobItemDTOStatus = typeof PlaylistImportJobItemDTOStatus[keyof typeof PlaylistImportJobItemDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlaylistImportJobItemDTOStatus = {
  PENDING: 'PENDING',
  ALREADY_KNOWN: 'ALREADY_KNOWN',
  RESOLVED: 'RESOLVED',
  UNRESOLVED: 'UNRESOLVED',
} as const;
