/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistMemberDTO } from './playlistMemberDTO';

export interface PlaylistInvitePreviewDTO {
  name?: string;
  color?: string;
  songCount?: number;
  members?: PlaylistMemberDTO[];
}
