/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PlayerCardDTO {
  songId?: number;
  artist?: string;
  title?: string;
  releaseYear?: number;
  color?: string;
  position?: number;
}
