/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PlaylistImportJobDTOStatus = typeof PlaylistImportJobDTOStatus[keyof typeof PlaylistImportJobDTOStatus];


export const PlaylistImportJobDTOStatus = {
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;
