/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistMemberDTO } from './playlistMemberDTO';
import type { SongDTO } from './songDTO';

export interface PlaylistDetailDTO {
  id: number;
  name: string;
  color: string;
  description?: string;
  inviteCode: string;
  songCount: number;
  songs?: SongDTO[];
  ownerId: number;
  members: PlaylistMemberDTO[];
  isPublic?: boolean;
}
