/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PlaylistImportJobDTOStatus = typeof PlaylistImportJobDTOStatus[keyof typeof PlaylistImportJobDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlaylistImportJobDTOStatus = {
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;
