/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PlaylistMemberDTO {
  userId?: number;
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  owner?: boolean;
  canRead?: boolean;
  canWrite?: boolean;
  canDelete?: boolean;
  joinedAt?: string;
}
