/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistImportJobDTOStatus } from './playlistImportJobDTOStatus';
import type { PlaylistImportJobItemDTO } from './playlistImportJobItemDTO';

export interface PlaylistImportJobDTO {
  id?: string;
  playlistId?: number;
  status?: PlaylistImportJobDTOStatus;
  createdAt?: string;
  completedAt?: string;
  items?: PlaylistImportJobItemDTO[];
}
