/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlayerDTOStatus } from './playerDTOStatus';
import type { PlayerCardDTO } from './playerCardDTO';

export interface PlayerDTO {
  id?: number;
  userId?: number;
  displayName?: string;
  avatarUrl?: string;
  turnOrder?: number;
  tokenCount?: number;
  status?: PlayerDTOStatus;
  isConnected?: boolean;
  totalArtistsGuessed?: number;
  totalTitlesGuessed?: number;
  timeline?: PlayerCardDTO[];
}
