/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PlayerResultDTO {
  playerId?: number;
  displayName?: string;
  cardCount?: number;
  rank?: number;
}
