/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PlayerDTOStatus = typeof PlayerDTOStatus[keyof typeof PlayerDTOStatus];


export const PlayerDTOStatus = {
  ACTIVE: 'ACTIVE',
  LEFT: 'LEFT',
} as const;
