/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserSummaryDTO } from './userSummaryDTO';

export interface PublicPlaylistSummaryDTO {
  id: number;
  name: string;
  color: string;
  songCount: number;
  owner: UserSummaryDTO;
  previewYoutubeIds: string[];
}
