/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SongDTO } from './songDTO';

export interface RecommendedSongsDTO {
  songs?: SongDTO[];
  hasMore?: boolean;
}
