/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterRequest {
  /**
     * @minLength 3
     * @maxLength 20
     */
  username: string;
  /** @minLength 1 */
  email: string;
  /**
     * @minLength 6
     * @maxLength 2147483647
     */
  password: string;
}
