/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ResolveReportRequestVerificationStatus } from './resolveReportRequestVerificationStatus';

export interface ResolveReportRequest {
  /** @minimum 1000 */
  correctedYear?: number;
  verificationStatus: ResolveReportRequestVerificationStatus;
}
