/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BetDTO } from './betDTO';
import type { RoundDTOStatus } from './roundDTOStatus';

export interface RoundDTO {
  id?: number;
  roundNumber?: number;
  activePlayerId?: number;
  djPlayerId?: number;
  status?: RoundDTOStatus;
  placedPosition?: number;
  placementCorrect?: boolean;
  bets?: BetDTO[];
  revealedArtist?: string;
  revealedTitle?: string;
  revealedYear?: number;
  revealedColor?: string;
  countdownEndsAt?: string;
  bettingWindowEndsAt?: string;
  nextRoundStartsAt?: string;
}
