/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RoundDTOStatus } from './roundDTOStatus';

export interface RoundDTO {
  id?: number;
  roundNumber?: number;
  activePlayerId?: number;
  djPlayerId?: number;
  status?: RoundDTOStatus;
  placedPosition?: number;
  placementCorrect?: boolean;
  bettorPlayerId?: number;
  revealedArtist?: string;
  revealedTitle?: string;
  revealedYear?: number;
}
