/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RoundDTOStatus = typeof RoundDTOStatus[keyof typeof RoundDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoundDTOStatus = {
  AWAITING_PLACEMENT: 'AWAITING_PLACEMENT',
  COUNTDOWN: 'COUNTDOWN',
  BETTING: 'BETTING',
  REVEALED: 'REVEALED',
  SCORED: 'SCORED',
} as const;
