/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RoundDTOStatus = typeof RoundDTOStatus[keyof typeof RoundDTOStatus];


export const RoundDTOStatus = {
  AWAITING_PLACEMENT: 'AWAITING_PLACEMENT',
  COUNTDOWN: 'COUNTDOWN',
  BETTING: 'BETTING',
  REVEALED: 'REVEALED',
  SCORED: 'SCORED',
} as const;
