/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RoundLinkOutDTO {
  roundId?: number;
  roundNumber?: number;
  youtubeId?: string;
  watchUrl?: string;
  artist?: string;
  title?: string;
  releaseYear?: number;
  color?: string;
}
