/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlayerResultDTO } from './playerResultDTO';
import type { LeaderboardEntryDTO } from './leaderboardEntryDTO';

export interface SessionResultsDTO {
  groupId?: number;
  cardCountRanking?: PlayerResultDTO[];
  mostArtistsGuessed?: LeaderboardEntryDTO[];
  mostTitlesGuessed?: LeaderboardEntryDTO[];
}
