/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SongArtistDTORole = typeof SongArtistDTORole[keyof typeof SongArtistDTORole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SongArtistDTORole = {
  MAIN: 'MAIN',
  FEATURED: 'FEATURED',
} as const;
