/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SongArtistDTO } from './songArtistDTO';
import type { SongDTOTagsItem } from './songDTOTagsItem';
import type { SongDTOCountry } from './songDTOCountry';
import type { SongDTOVerificationStatus } from './songDTOVerificationStatus';
import type { UserSummaryDTO } from './userSummaryDTO';

export interface SongDTO {
  id: number;
  artists: SongArtistDTO[];
  title: string;
  releaseYear: number;
  youtubeId: string;
  gradientColor1?: string;
  gradientColor2?: string;
  tags?: SongDTOTagsItem[];
  country?: SongDTOCountry;
  verificationStatus: SongDTOVerificationStatus;
  confidence?: string;
  addedBy: UserSummaryDTO;
}
