/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SongMetadataResponse {
  title?: string;
  artist?: string;
  releaseYear?: number;
  color?: string;
  confidence?: string;
  source?: string;
  reasoning?: string;
  verificationStatus?: string;
}
