/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SongArtistDTO } from './songArtistDTO';
import type { SongDTOCountry } from './songDTOCountry';
import type { SongDTOVerificationStatus } from './songDTOVerificationStatus';
import type { UserSummaryDTO } from './userSummaryDTO';

export interface SongDTO {
  id: number;
  artists: SongArtistDTO[];
  title: string;
  releaseYear: number;
  youtubeId: string;
  color?: string;
  genre?: string;
  country?: SongDTOCountry;
  verificationStatus: SongDTOVerificationStatus;
  confidence?: string;
  needsUserAttention?: boolean;
  addedBy?: UserSummaryDTO;
}
