/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SongDTOCountry = typeof SongDTOCountry[keyof typeof SongDTOCountry];


export const SongDTOCountry = {
  NONE: 'NONE',
  RO: 'RO',
} as const;
