/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SongDTOTagsItem = typeof SongDTOTagsItem[keyof typeof SongDTOTagsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SongDTOTagsItem = {
  PLAYLIST: 'PLAYLIST',
  SPECIAL: 'SPECIAL',
  ANIME: 'ANIME',
} as const;
