/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SongArtistDTORole = typeof SongArtistDTORole[keyof typeof SongArtistDTORole];


export const SongArtistDTORole = {
  MAIN: 'MAIN',
  FEATURED: 'FEATURED',
} as const;
