/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SongArtistDTORole } from './songArtistDTORole';

export interface SongArtistDTO {
  name?: string;
  role?: SongArtistDTORole;
}
