/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SongMetadataResponse {
  title?: string;
  mainArtists?: string[];
  featuredArtists?: string[];
  releaseYear?: number;
  color?: string;
  confidence?: string;
  source?: string;
  reasoning?: string;
  verificationStatus?: string;
  sitelinksCount?: number;
}
