/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SubmitReportRequest {
  /** @minLength 1 */
  message: string;
  /** @minimum 1000 */
  suggestedCorrectYear?: number;
  sources?: string;
}
