/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TwoFactorVerifyRequest {
  /** @minLength 1 */
  pendingToken: string;
  /** @minLength 1 */
  code: string;
}
