/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdatePlaylistRequest {
  name?: string;
  /** @pattern (?i)^(cba6f7|fab387|a6e3a1|89b4fa|f5c2e7|f9e2af)$ */
  color?: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  description?: string;
}
