/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateGroupSettingsRequestDjMode } from './updateGroupSettingsRequestDjMode';

export interface UpdateGroupSettingsRequest {
  playlistIds?: number[];
  djMode?: UpdateGroupSettingsRequestDjMode;
  winConditionCardCount?: number;
  fixedDjMemberId?: number;
}
