/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdatePlaylistRequest {
  name?: string;
  /** @pattern ^[0-9a-fA-F]{6}$ */
  color?: string;
}
