/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateUserRequest {
  /**
     * @minLength 3
     * @maxLength 20
     */
  username?: string;
  email?: string;
}
