/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateGroupSettingsRequestDjMode = typeof UpdateGroupSettingsRequestDjMode[keyof typeof UpdateGroupSettingsRequestDjMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateGroupSettingsRequestDjMode = {
  FIXED: 'FIXED',
  ROTATING: 'ROTATING',
} as const;
