/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateSongRequestCountry = typeof UpdateSongRequestCountry[keyof typeof UpdateSongRequestCountry];


export const UpdateSongRequestCountry = {
  NONE: 'NONE',
  RO: 'RO',
} as const;
