/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateGroupSettingsRequestDjMode = typeof UpdateGroupSettingsRequestDjMode[keyof typeof UpdateGroupSettingsRequestDjMode];


export const UpdateGroupSettingsRequestDjMode = {
  FIXED: 'FIXED',
  ROTATING: 'ROTATING',
} as const;
