/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateSongRequestCountry } from './updateSongRequestCountry';

export interface UpdateSongRequest {
  /** @minLength 1 */
  artist: string;
  /** @minLength 1 */
  title: string;
  /** @minimum 1000 */
  releaseYear?: number;
  /**
   * @minLength 1
   * @pattern ^[a-zA-Z0-9_-]{11}$
   */
  youtubeId: string;
  /**
   * @minLength 1
   * @pattern ^[0-9a-fA-F]{6}$
   */
  gradientColor1: string;
  /**
   * @minLength 1
   * @pattern ^[0-9a-fA-F]{6}$
   */
  gradientColor2: string;
  country?: UpdateSongRequestCountry;
}
