/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistSummaryDTO } from './playlistSummaryDTO';

export interface UserDetailDTO {
  id?: number;
  username?: string;
  email?: string;
  imageUrl?: string;
  provider?: string;
  playlists?: PlaylistSummaryDTO[];
}
