/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Get all playlists of current user
 */
export const GetUserPlaylistsResponse = zod.unknown()

/**
 * @summary Create new playlist for current user
 */
export const CreatePlaylistResponse = zod.unknown()

/**
 * @summary Join an existing playlist, optionally with a per-playlist display name and avatar
 */
export const JoinPlaylistParams = zod.object({
  "playlistInviteCode": zod.string()
})

export const JoinPlaylistBody = zod.object({
  "displayName": zod.string().optional(),
  "avatarUrl": zod.string().optional()
})

export const JoinPlaylistResponse = zod.unknown()

/**
 * @summary Get current user information
 */
export const GetCurrentUserResponse = zod.unknown()

/**
 * @summary Delete current user
 */
export const DeleteUserResponse = zod.unknown()

/**
 * @summary Update current user information
 */
export const updateUserBodyUsernameMin = 3;
export const updateUserBodyUsernameMax = 20;



export const UpdateUserBody = zod.object({
  "username": zod.string().min(updateUserBodyUsernameMin).max(updateUserBodyUsernameMax).optional(),
  "email": zod.email().optional()
})

export const UpdateUserResponse = zod.unknown()

/**
 * @summary Get user information by ID
 */
export const GetUserParams = zod.object({
  "userId": zod.int()
})

export const GetUserResponse = zod.unknown()

/**
 * @summary Get the current user's saved public playlists
 */
export const GetSavedPlaylistsResponse = zod.unknown()

/**
 * @summary Export the current user's own account, playlist, and song data for GDPR purposes
 */
export const ExportPersonalDataResponse = zod.unknown()

/**
 * @summary Leave playlist
 */
export const LeavePlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const LeavePlaylistResponse = zod.unknown()

