/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Unpublish a playlist, owner only
 */
export const UnpublishPlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const UnpublishPlaylistResponse = zod.unknown()

/**
 * @summary Add a new song to the playlist
 */
export const CreateSongParams = zod.object({
  "playlistId": zod.int()
})



export const createSongBodyReleaseYearMin = 1000;



export const createSongBodyYoutubeIdRegExp = new RegExp('^[a-zA-Z0-9_-]{11}$');


export const createSongBodyColorRegExp = new RegExp('^[0-9a-fA-F]{6}$');


export const CreateSongBody = zod.object({
  "artist": zod.string().min(1),
  "title": zod.string().min(1),
  "releaseYear": zod.int().min(createSongBodyReleaseYearMin).optional(),
  "youtubeId": zod.string().min(1).regex(createSongBodyYoutubeIdRegExp),
  "color": zod.string().min(1).regex(createSongBodyColorRegExp),
  "country": zod.enum(['NONE', 'RO']).optional(),
  "metadataConfirmed": zod.boolean().optional()
})

export const CreateSongResponse = zod.unknown()

/**
 * @summary Save a public playlist into the current user's own library, without becoming a member
 */
export const SavePlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const SavePlaylistResponse = zod.unknown()

/**
 * @summary Unsave a previously saved playlist
 */
export const UnsavePlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const UnsavePlaylistResponse = zod.unknown()

/**
 * @summary Publish a playlist publicly, owner only
 */
export const PublishPlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const PublishPlaylistResponse = zod.unknown()

/**
 * @summary Transfer ownership to another member, owner only; the previous owner stays a regular member
 */
export const PromoteMemberParams = zod.object({
  "playlistId": zod.int(),
  "userId": zod.int()
})

export const PromoteMemberResponse = zod.unknown()

/**
 * @summary Ban a member, owner only; blocks their future join attempts
 */
export const BanMemberParams = zod.object({
  "playlistId": zod.int(),
  "userId": zod.int()
})

export const BanMemberResponse = zod.unknown()

/**
 * @summary Copy the songs of a source playlist into this playlist, skipping songs already present
 */
export const ImportFromPlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const ImportFromPlaylistBody = zod.object({
  "sourcePlaylistId": zod.int()
})

export const ImportFromPlaylistResponse = zod.unknown()

/**
 * @summary Get playlist information
 */
export const GetPlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const GetPlaylistResponse = zod.unknown()

/**
 * @summary Delete a playlist, owner only
 */
export const DeletePlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const DeletePlaylistResponse = zod.unknown()

/**
 * @summary Update playlist information
 */
export const UpdatePlaylistParams = zod.object({
  "playlistId": zod.int()
})

export const updatePlaylistBodyColorRegExp = new RegExp('(?i)^(cba6f7|fab387|a6e3a1|89b4fa|f5c2e7|f9e2af)$');
export const updatePlaylistBodyDescriptionMin = 0;
export const updatePlaylistBodyDescriptionMax = 300;



export const UpdatePlaylistBody = zod.object({
  "name": zod.string().optional(),
  "color": zod.string().regex(updatePlaylistBodyColorRegExp).optional(),
  "description": zod.string().min(updatePlaylistBodyDescriptionMin).max(updatePlaylistBodyDescriptionMax).optional()
})

export const UpdatePlaylistResponse = zod.unknown()

/**
 * @summary Get information about a particular song in the playlist
 */
export const GetSongParams = zod.object({
  "playlistId": zod.int(),
  "songId": zod.int()
})

export const GetSongResponse = zod.unknown()

/**
 * @summary Delete song from the playlist
 */
export const DeleteSongParams = zod.object({
  "playlistId": zod.int(),
  "songId": zod.int()
})

export const DeleteSongResponse = zod.unknown()

/**
 * @summary Edit information about a particular song in the playlist
 */
export const UpdateSongParams = zod.object({
  "playlistId": zod.int(),
  "songId": zod.int()
})



export const updateSongBodyReleaseYearMin = 1000;



export const updateSongBodyYoutubeIdRegExp = new RegExp('^[a-zA-Z0-9_-]{11}$');


export const updateSongBodyColorRegExp = new RegExp('^[0-9a-fA-F]{6}$');


export const UpdateSongBody = zod.object({
  "artist": zod.string().min(1),
  "title": zod.string().min(1),
  "releaseYear": zod.int().min(updateSongBodyReleaseYearMin).optional(),
  "youtubeId": zod.string().min(1).regex(updateSongBodyYoutubeIdRegExp),
  "color": zod.string().min(1).regex(updateSongBodyColorRegExp),
  "country": zod.enum(['NONE', 'RO']).optional()
})

export const UpdateSongResponse = zod.unknown()

/**
 * @summary Kick a member, owner only; the invite still lets them rejoin
 */
export const KickMemberParams = zod.object({
  "playlistId": zod.int(),
  "userId": zod.int()
})

export const KickMemberResponse = zod.unknown()

/**
 * @summary Update a member's read, write, and delete grants, owner only
 */
export const UpdateMemberGrantsParams = zod.object({
  "playlistId": zod.int(),
  "userId": zod.int()
})

export const UpdateMemberGrantsBody = zod.object({
  "canRead": zod.boolean().optional(),
  "canWrite": zod.boolean().optional(),
  "canDelete": zod.boolean().optional()
})

export const UpdateMemberGrantsResponse = zod.unknown()

/**
 * @summary Get the playlist's members and their per-playlist identity and grants
 */
export const GetMembersParams = zod.object({
  "playlistId": zod.int()
})

export const GetMembersResponse = zod.unknown()

/**
 * @summary Browse every playlist published publicly
 */
export const GetPublicPlaylistsResponse = zod.unknown()

/**
 * @summary Preview a playlist by invite code, no membership or authentication required
 */
export const GetInvitePreviewParams = zod.object({
  "inviteCode": zod.string()
})

export const GetInvitePreviewResponse = zod.unknown()

